apiVersion: v1
data:
  APP_ENV: kubernetes
  CATALOG_URL: http://catalog:8081
  ORDERS_URL: http://orders:8082
  STOREFRONT_URL: http://storefront:8080
  DATA_FILE: /data/orders.json
kind: ConfigMap
metadata:
  name: microshop-config
  namespace: microshop
