apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
  namespace: microshop
spec:
  ports:
  - name: 80-8081
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: catalog
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders
  name: orders
  namespace: microshop
spec:
  ports:
  - name: 80-8082
    port: 8082
    protocol: TCP
    targetPort: http
  selector:
    app: orders
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storefront
  name: storefront
  namespace: microshop
spec:
  ports:
  - name: 80-8080
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: storefront
  type: ClusterIP
